# =========================================================
# APPLICATION
# =========================================================
spring.application.name=wallet
server.port=8085


# =========================================================
# DATABASE - PostgreSQL / Neon  For testing purpose
# =========================================================
spring.datasource.url=jdbc:postgresql://ep-floral-cake-azozqgqd-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sCUnXdul40jr
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP connection pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


# =========================================================
# JPA / HIBERNATE
# =========================================================
# Development setting. Replace with Flyway migrations before production.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQL logging - useful during development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# TRANSACTIONS / TIME
# =========================================================
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# =========================================================
# SERVER ERROR RESPONSES
# =========================================================
server.error.include-message=always
server.error.include-binding-errors=always
